-- --- Tablas ---
CREATE TABLE "Usuarios" (
  "usuario_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "contrasena_hash" varchar(255) NOT NULL,
  "telefono" varchar(50),
  "rol_id" integer NOT NULL,
  "fecha_creacion" timestamp DEFAULT (now()),
  "ultimo_login" timestamp
);
CREATE TABLE "Roles" (
  "rol_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_rol" varchar(50) UNIQUE NOT NULL
);
CREATE TABLE "Proyectos" (
  "proyecto_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "descripcion" text,
  "fecha_inicio" date,
  "fecha_fin" date,
  "gestor_id" integer,
  "esta_archivado" boolean NOT NULL DEFAULT false,
  "fecha_creacion" timestamp DEFAULT (now())
);
CREATE TABLE "Tareas" (
  "tarea_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "proyecto_id" integer NOT NULL,
  "titulo" varchar(255) NOT NULL,
  "descripcion" text,
  "estado" varchar(50) NOT NULL DEFAULT 'Pendiente de Asignar',
  "prioridad" varchar(50) NOT NULL DEFAULT 'Media',
  "asignado_id" integer,
  "fecha_limite" date,
  "fecha_creacion" timestamp DEFAULT (now()),
  "fecha_actualizacion" timestamp DEFAULT (now())
);
CREATE TABLE "Comentarios" (
  "comentario_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tarea_id" integer NOT NULL,
  "usuario_id" integer NOT NULL,
  "texto_comentario" text NOT NULL,
  "fecha_creacion" timestamp DEFAULT (now())
);
CREATE TABLE "Equipos" (
  "equipo_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) UNIQUE NOT NULL,
  "fecha_creacion" timestamp DEFAULT (now()),
  "conversacion_id" integer
);
CREATE TABLE "MiembrosEquipo" (
  "usuario_id" integer,
  "equipo_id" integer,
  "fecha_asignacion" timestamp DEFAULT (now()),
  PRIMARY KEY ("usuario_id", "equipo_id")
);
CREATE TABLE "RegistrosHorarios" (
  "registro_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "inicio_jornada" timestamp NOT NULL,
  "fin_jornada" timestamp,
  "duracion_segundos" integer,
  "fecha_registro" date NOT NULL
);
CREATE TABLE "Notificaciones" (
  "notificacion_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "mensaje" text NOT NULL,
  "leida" boolean NOT NULL DEFAULT false,
  "tarea_relacionada_id" integer,
  "fecha_creacion" timestamp DEFAULT (now())
);
CREATE TABLE "Conversaciones" (
  "conversacion_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "es_grupo" boolean NOT NULL DEFAULT false,
  "fecha_creacion" timestamp DEFAULT (now()),
  "ultima_actividad" timestamp DEFAULT (now())
);
CREATE TABLE "ParticipantesConversacion" (
  "usuario_id" integer,
  "conversacion_id" integer,
  "fecha_union" timestamp DEFAULT (now()),
  PRIMARY KEY ("usuario_id", "conversacion_id")
);
CREATE TABLE "Mensajes" (
  "mensaje_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversacion_id" integer NOT NULL,
  "remitente_id" integer NOT NULL,
  "texto_mensaje" text NOT NULL,
  "fecha_envio" timestamp DEFAULT (now())
);
-- --- Índices ---
CREATE INDEX ON "Usuarios" ("email");
CREATE INDEX ON "RegistrosHorarios" ("usuario_id", "fecha_registro");
CREATE INDEX ON "ParticipantesConversacion" ("conversacion_id");
CREATE INDEX ON "Mensajes" ("conversacion_id", "fecha_envio");
-- --- Comentarios ---
COMMENT ON COLUMN "Usuarios"."contrasena_hash" IS 'Almacenar solo contraseñas hasheadas';
COMMENT ON COLUMN "Roles"."nombre_rol" IS 'Administrador, Gestor, Trabajador, Colaborador';
COMMENT ON COLUMN "Proyectos"."gestor_id" IS 'FK a Usuarios, normalmente Gestor o Admin';
COMMENT ON COLUMN "Tareas"."estado" IS 'Pendiente de Asignar, Pendiente, En Progreso, Bloqueada, Finalizado';
COMMENT ON COLUMN "Tareas"."prioridad" IS 'Baja, Media, Alta';
COMMENT ON COLUMN "Tareas"."asignado_id" IS 'FK a Usuarios';
COMMENT ON COLUMN "Equipos"."conversacion_id" IS 'FK a Conversaciones para chat grupal';
COMMENT ON COLUMN "RegistrosHorarios"."fin_jornada" IS 'Nulo si está actualmente fichado';
COMMENT ON COLUMN "RegistrosHorarios"."duracion_segundos" IS 'Calculado al finalizar jornada';
COMMENT ON COLUMN "RegistrosHorarios"."fecha_registro" IS 'Fecha desnormalizada para facilitar consultas por día';
COMMENT ON COLUMN "Notificaciones"."usuario_id" IS 'Usuario destinatario';
COMMENT ON COLUMN "Conversaciones"."ultima_actividad" IS 'Para ordenar conversaciones';
-- --- Relaciones (Claves Foráneas) ---
ALTER TABLE "MiembrosEquipo" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuarios" ("usuario_id");
ALTER TABLE "MiembrosEquipo" ADD FOREIGN KEY ("equipo_id") REFERENCES "Equipos" ("equipo_id");
ALTER TABLE "ParticipantesConversacion" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuarios" ("usuario_id");
ALTER TABLE "ParticipantesConversacion" ADD FOREIGN KEY ("conversacion_id") REFERENCES "Conversaciones" ("conversacion_id");
ALTER TABLE "Usuarios" ADD FOREIGN KEY ("rol_id") REFERENCES "Roles" ("rol_id");
ALTER TABLE "Proyectos" ADD FOREIGN KEY ("gestor_id") REFERENCES "Usuarios" ("usuario_id");
ALTER TABLE "Tareas" ADD FOREIGN KEY ("asignado_id") REFERENCES "Usuarios" ("usuario_id");
ALTER TABLE "Comentarios" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuarios" ("usuario_id");
ALTER TABLE "RegistrosHorarios" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuarios" ("usuario_id");
ALTER TABLE "Notificaciones" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuarios" ("usuario_id");
ALTER TABLE "Mensajes" ADD FOREIGN KEY ("remitente_id") REFERENCES "Usuarios" ("usuario_id");
ALTER TABLE "Tareas" ADD FOREIGN KEY ("proyecto_id") REFERENCES "Proyectos" ("proyecto_id");
ALTER TABLE "Comentarios" ADD FOREIGN KEY ("tarea_id") REFERENCES "Tareas" ("tarea_id");
ALTER TABLE "Notificaciones" ADD FOREIGN KEY ("tarea_relacionada_id") REFERENCES "Tareas" ("tarea_id");
ALTER TABLE "Equipos" ADD FOREIGN KEY ("conversacion_id") REFERENCES "Conversaciones" ("conversacion_id");
ALTER TABLE "Mensajes" ADD FOREIGN KEY ("conversacion_id") REFERENCES "Conversaciones" ("conversacion_id");